# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:cs.*'

# 検索キーワード
keywords:
    quantum computer: 5
    quantum information: 4
    quantum algorithm: 5
    generative model: 1
    optimisation: 3
    tensor network: 4
    statistical mechanics: 3
    Statistical physics: 3
    MCMC: 3
    phase transition: 4
    RUC: 4
    ising: 1

# 通知の閾値
score_threshold: 2
